from apps.home_app import HomeApp
from apps.walsh_app import WalshApp
from apps.walsh_app_secure import WalshAppSecure
from apps.login_app import LoginApp
from apps.member_app import MemberApp
from apps.spacy_nlp import SpacyNLP
from apps.pred_app import PredictApp
from apps.Howto_app import HowtoApp
from apps.intro_app import IntroApp
from apps.myloading_app import MyLoadingApp
from apps.signup import SignUpApp
from apps.contact_us import ContactUsAPP
from apps.dashb_app import DashbApp
